travis:
  secure:
    BINSTAR_TOKEN: YxUg6a/ZqlG30Vz2027jqJNxseFR+sYGhlSk2BsaRAL2dzl2Kq6sgBM43o5FyrxSL4m0+fcULSDbqV5G6z3PSgDWgZTxlgWRpvQAKAw+3tC6gOFtMgm48ts7UjHU2SSqiQ78EZPaDtVuoDlpNy8tfn0/T4XjPMV7N+eLzh/NQ3SkHLdhCyzy7Tnh2oNzMEVwddDMWzfdmp62EwhReT3c3vyHMDBIsuO+vQ/BPshnQbxozKhHpvPczGrc4N7ZaJfE46Mqf7dQtzDCLXq9jQP7RelYyaMashketm2hp5mSpMveYLqHqIBcgCaBviK1YuWm/eQmeILKJA8tno48Ynp1dPwBvb/2dkJ/BHq8oy8Pgriuq8wyKTBz269rz411PVRioO3d6OKUAZ1MEIlwcUOp6hRVcqG+J8KnetKq+a/tXcmKk8zBHVBHhw2GDQ9VC6rmtjc/3kFKHxUKLQ/l/aB72qo8afm3BeH3klQIiJWRgHrpGvmo/yTrli+9UKJb33JQeg1+uYZGcEb6XLlF1xoVMY/J85jP/PBj+KHydg/wqJY0MN8nMhd0w+laBaP94SuM3eoghg456fAMb+Iz8J3Xtyzh6MB3qluhDb8FcFHrUmf7+cckpXvtflgPzBbDYZ7b9OK6bsh2rZp7te92Y7peFE9oLeUz9OF8cBtBQyWLFPg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
