travis:
  secure:
    BINSTAR_TOKEN: bRVpw4xiHXlc+AbYEGoTTwgtxvhwUONCMorIQYq7x6yqw3gN1sMgH0fxTUMJuIFRDFlzJ31mi1kd9OPQ6WTnTaOSrK8/vymC6OQY5O2Ohu9NKxhdPFiZJ+wZGMlyQEfrjKv+LHPd3Thgf+wTng2JPzwZ56v7TpP7kYhb3XUq5aFb1YBQAY/lSo58B06ccRN1Xg92doeQrOzEC38JpV3lvLsSRC1znHt0SGBos3Pf10556T7G3eLVgrvCyuki2MpIJHxTNr/+gBu0TUA5qeZQtTmGAp4Elc7/Nc61wF9e09TW8ZjJXi4R/wur7jCF+gNSxxosCFKPno+E+HG8F4MXdzpOfilrGATXNGI4kNkdGtVPwhAm9DwfE8YnF7+tBCGK3M6e6y5i7vdZzJySEeFrVT9lKix/909pfbMYaXOh5ApgVA/BDeQYQVFn+ucUD9W+RrmgLbmLWFP0CDUhb/Yv1zSO+vQb+hNcU22w8fRKveaVVBxEb234+Z17EdcobQ+v1WJ7tJztnkIuK0ZkrQ9QRQ233601tGRn6tqPIcxXXt1jSkVASv3IEX1Kt6KJQ+OCciK82xlFlk1Zdaz/ryuU1zCE3esYRyvM+YrypTprPIhN/PMC0/2dtf2OxBQDGL2Kw/azIbh7g8TrqrcnmYAEfYi1GbCZZ0EXjUeYmC0I90I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
