travis:
  secure:
    BINSTAR_TOKEN: ydm5vTRGGE/z4nfcWvajplOq7m+EjPpqWKCAcbj9CJFE1wX5gFCqyzn9juaRuoYwcGoPgNYZp0eyz64dVv/PTHOq8e6YQTMRAHhYWZQKUCmNAZ6wiKaT6dmH44ddCiM5qoYyRlJj2vqvsjAsJSwrENhbBNfqwuF3v7LbQ4aHCGNwqXrKt0gcEdDKVaDuPkcCz3egVUvCGbFxejSpdxlSGg7pIImUWc05YIKW1bdsLaVf2bmaxr0kZrC3/5DV6f2KDDVYQPfxooyKb5xGDK0+CfnDEMU6tgEkIY7Ms2SxVWj41YMqYLaRUo+Dx7+Vxvm+hWKvNnAdJKhvoU/3n5b4d3PIS4YD5jRQc5RsHZmH5X9Jq8YviWv/JJ0vyRjW7TSI242dVgXUYy8dXyyz5j+646rw0/emr5tT7r4itcnO4KmbP/Kt2Cb2Ugzb9ciqgxpO2KWLvfTLkdaK8KsXZUx7BXoywBWGwCqORcp8a9C63sb/uCmLBe5e9dt7fIHeSjmuu/+H/lkeyCTXfkIWKpdOReKxkyglT9A1LPHKQUCtb/xu1JEKwbseN3LlyF5t0G/LwNcXWq4iADa9uDQREI+MlbHcO5aaacF6+eEXQSLxWpOoF/PuJYYhAZjE12/nFUj0wiSn//fl7ITjEy7uSKYgtbguASnWaXkeOQBQjQccz3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
